name = "kernel"
version = "0.1.0"
defaultTargets = ["kernel"]

[[lean_exe]]
name = "kernel"
root = "Main"

[[require]]
scope = "leanprover"
name = "lean4export"
rev = "json_parse"

[[require]]
scope = "leanprover"
name = "Lean4Checker"
rev = "b7398199245524275543dec6113229c9bb4902e5"